In [2]:
 import numpy as np
 import pandas as pd
 all_data=pd.read_csv("/content/1686715083343_all_data (2).csv")
 all_data.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176559.0,Bose SoundSport Headphones,1.0,99.99,4/7/2019 22:30,"682 Chestnut St, Boston, MA 02215"
1,176560.0,Google Phone,1.0,600.00,4/12/2019 14:38,"669 Spruce St, Los Angeles, CA 90001"
2,176560.0,Wired Headphones,1.0,11.99,4/12/2019 14:38,"669 Spruce St, Los Angeles, CA 90001"
3,176561.0,Wired Headphones,1.0,11.99,5/30/2019 9:27,"333 8th St, Los Angeles, CA 90001"
4,176562.0,USB-C Charging Cable,1.0,11.95,4/29/2019 13:03,"381 Wilson St, San Francisco, CA 94016"

In [10]:
#clean up the data
all_data.shape

(69, 6)

In [26]:
	# drop rows of nan
  nan_df=all_data[all_data.isna().any(axis=1)]
  display(nan_df.head())

IndentationError: ignored

In [5]:
all_data.shape

(69, 6)

In [15]:
all_data=all_data.dropna(how='all')
all_data.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176559.0,Bose SoundSport Headphones,1.0,99.99,4/7/2019 22:30,"682 Chestnut St, Boston, MA 02215"
1,176560.0,Google Phone,1.0,600.00,4/12/2019 14:38,"669 Spruce St, Los Angeles, CA 90001"
2,176560.0,Wired Headphones,1.0,11.99,4/12/2019 14:38,"669 Spruce St, Los Angeles, CA 90001"
3,176561.0,Wired Headphones,1.0,11.99,5/30/2019 9:27,"333 8th St, Los Angeles, CA 90001"
4,176562.0,USB-C Charging Cable,1.0,11.95,4/29/2019 13:03,"381 Wilson St, San Francisco, CA 94016"

In [16]:
#get rid of text order date column
all_data=all_data[all_data['Order Date'].str[0:2]!='or']
print(all_data)

    Order ID                     Product  Quantity Ordered  Price Each  \
0   176559.0  Bose SoundSport Headphones               1.0       99.99
1   176560.0                Google Phone               1.0      600.00
2   176560.0            Wired Headphones               1.0       11.99
3   176561.0            Wired Headphones               1.0       11.99
4   176562.0        USB-C Charging Cable               1.0       11.95
..       ...                         ...               ...         ...
64  259329.0    Lightning Charging Cable               1.0       14.95
65  259330.0       AA Batteries (4-pack)               2.0        3.84
66  259331.0    Apple Airpods Headphones               1.0      150.00
67  259332.0    Apple Airpods Headphones               1.0      150.00
68  259333.0  Bose SoundSport Headphones               1.0       99.99

         Order Date                        Purchase Address
0    4/7/2019 22:30       682 Chestnut St, Boston, MA 02215
1   4/12/2019 14:38    669 Spruce St, Los Angeles, CA 90001
2   4/12/2019 14:38    669 Spruce St, Los Angeles, CA 90001
3    5/30/2019 9:27       333 8th St, Los Angeles, CA 90001
4   4/29/2019 13:03  381 Wilson St, San Francisco, CA 94016
..              ...                                     ...
64   9/5/2019 19:00       480 Lincoln St, Atlanta, GA 30301
65  9/25/2019 22:01    763 Washington St, Seattle, WA 98101
66   9/29/2019 7:00     770 4th St, New York City, NY 10001
67  9/16/2019 19:21          782 Lake St, Atlanta, GA 30301
68  9/19/2019 18:03   347 Ridge St, San Francisco, CA 94016

[67 rows x 6 columns]

In [17]:
#make column correct type
all_data['Quantity Ordered']=pd.to_numeric(all_data['Quantity Ordered'])
all_data['Price Each']=pd.to_numeric(all_data['Price Each'])
all_data.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176559.0,Bose SoundSport Headphones,1.0,99.99,4/7/2019 22:30,"682 Chestnut St, Boston, MA 02215"
1,176560.0,Google Phone,1.0,600.00,4/12/2019 14:38,"669 Spruce St, Los Angeles, CA 90001"
2,176560.0,Wired Headphones,1.0,11.99,4/12/2019 14:38,"669 Spruce St, Los Angeles, CA 90001"
3,176561.0,Wired Headphones,1.0,11.99,5/30/2019 9:27,"333 8th St, Los Angeles, CA 90001"
4,176562.0,USB-C Charging Cable,1.0,11.95,4/29/2019 13:03,"381 Wilson St, San Francisco, CA 94016"

In [23]:
#Add city column
def get_city(adress):
  return address.split(",")[1].strip(" ")
  def get_state(address):
    return address.split(",")[2].strip(" ")[1]
    all_data['city']=all_data['Purchase Address'].apply(lambda x:f"{get_city(x)} ({get_state(x)})")
all_data.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176559.0,Bose SoundSport Headphones,1.0,99.99,4/7/2019 22:30,"682 Chestnut St, Boston, MA 02215"
1,176560.0,Google Phone,1.0,600.00,4/12/2019 14:38,"669 Spruce St, Los Angeles, CA 90001"
2,176560.0,Wired Headphones,1.0,11.99,4/12/2019 14:38,"669 Spruce St, Los Angeles, CA 90001"
3,176561.0,Wired Headphones,1.0,11.99,5/30/2019 9:27,"333 8th St, Los Angeles, CA 90001"
4,176562.0,USB-C Charging Cable,1.0,11.95,4/29/2019 13:03,"381 Wilson St, San Francisco, CA 94016"

In [25]:
#What was the best month for sales?how much was earned that month?
all_data['Sales']=all_data['Quantity Ordered'].astype('int')*all_data['Price Each'].astype('float')
all_data.groupby(['Month']).sum()

SyntaxError: ignored